sudo: required
services:
- docker

before_install:
- docker build -t learningdevsecops2020/docker-react -f Dockerfile.dev . 

script:
- docker run learningdevsecops2020/docker-react npm run test -- --coverage